// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#include "ui.h"
#include "nvs_flash.h"
#include "esp_wifi.h"
#include "opensky_client.h"
#include "radar.h"
#include "main.h"

/*
void wifi_connect_btn_cb(lv_event_t *e)
{
	// Your code here
}
	*/

static void msgbox_event_cb(lv_event_t *e)
{
	lv_obj_t *obj = lv_event_get_current_target(e);

	const char *txt =
		lv_msgbox_get_active_btn_text(obj);

	if (txt && strcmp(txt, "Forget") == 0)
	{
		nvs_handle_t handle;

		if (nvs_open("wifi",
					 NVS_READWRITE,
					 &handle) == ESP_OK)
		{
			nvs_erase_key(handle, "ssid");
			nvs_erase_key(handle, "pass");

			nvs_commit(handle);
			nvs_close(handle);
		}

		esp_wifi_disconnect();

		lv_label_set_text(
			uic_wifiName,
			"No WiFi Selected");

		lv_textarea_set_text(
			uic_wifiPassword,
			"");

		lv_textarea_set_text(
			uic_wifiStatus,
			"Not connected");
	}

	lv_msgbox_close(obj);
}

static void api_msgbox_event_cb(
	lv_event_t *e)
{
	lv_obj_t *obj =
		lv_event_get_current_target(e);

	const char *txt =
		lv_msgbox_get_active_btn_text(obj);

	if (txt &&
		strcmp(txt, "Forget") == 0)
	{
		nvs_handle_t handle;

		if (nvs_open(
				"opensky",
				NVS_READWRITE,
				&handle) == ESP_OK)
		{
			nvs_erase_key(
				handle,
				"client_id");

			nvs_erase_key(
				handle,
				"client_secret");

			nvs_commit(handle);

			nvs_close(handle);
		}

		esp_restart();
	}

	lv_msgbox_close(obj);
}

void forgetWifi(lv_event_t *e)
{
	static const char *btns[] =
		{
			"Cancel",
			"Forget",
			""};

	lv_obj_t *mbox =
		lv_msgbox_create(
			NULL,
			"Forget WiFi?",
			"Stored WiFi credentials will be removed.\n And device will be resetarted",
			btns,
			false);

	lv_obj_center(mbox);

	lv_obj_add_event_cb(
		mbox,
		msgbox_event_cb,
		LV_EVENT_VALUE_CHANGED,
		NULL);
}

void Radar_SelectPrev(lv_event_t *e)
{
	if (gAircraftCount <= 0)
	{
		selectedAircraft = -1;
		return;
	}

	selectedAircraft--;

	if (selectedAircraft < 0)
	{
		selectedAircraft =
			gAircraftCount - 1;
	}

	strcpy(
		selectedIcao24,
		gAircraft[selectedAircraft].icao24);

	Radar_Refresh();
	UpdateSelectedAircraftUI();
}

void Radar_SelectNext(lv_event_t *e)
{
	if (gAircraftCount <= 0)
	{
		selectedAircraft = -1;
		return;
	}

	selectedAircraft++;

	if (selectedAircraft >= gAircraftCount)
	{
		selectedAircraft = 0;
	}

	strcpy(
		selectedIcao24,
		gAircraft[selectedAircraft].icao24);

	Radar_Refresh();
	UpdateSelectedAircraftUI();
}

void showRadarSettings(lv_event_t *e)
{
	char value[24];

	lv_snprintf(value, sizeof(value), "%.4f", GetRadarLat());
	lv_textarea_set_text(uic_TextLat, value);
	lv_snprintf(value, sizeof(value), "%.4f", GetRadarLon());
	lv_textarea_set_text(uic_TextLon, value);
	lv_snprintf(value, sizeof(value), "%.0f", GetRadarRange());
	lv_textarea_set_text(uic_TextRange, value);
	lv_snprintf(value, sizeof(value), "%.0f", GetRadarPoll());
	lv_textarea_set_text(uic_TextPoll, value);
}

void editCoords(lv_event_t *e)
{
	float lat =
		atof(
			lv_textarea_get_text(
				uic_TextLat));

	float lon =
		atof(
			lv_textarea_get_text(
				uic_TextLon));

	float rangeKm =
		atof(
			lv_textarea_get_text(
				uic_TextRange));

	float pollSeconds =
		atof(
			lv_textarea_get_text(
				uic_TextPoll));

	SetRadarSettings(
		lat,
		lon,
		rangeKm,
		pollSeconds);

	Radar_Refresh();
}

void toggleLabels(lv_event_t *e)
{
	lv_event_code_t code =
		lv_event_get_code(e);

	lv_obj_t *obj =
		lv_event_get_target(e);

	if (code == LV_EVENT_VALUE_CHANGED)
	{
		showAircraftLabels =
			lv_obj_has_state(
				obj,
				LV_STATE_CHECKED);

		Radar_Refresh();

		LV_LOG_USER(
			"Labels: %s",
			showAircraftLabels
				? "On"
				: "Off");
	}
}

void forgetAPI(lv_event_t *e)
{
	static const char *btns[] =
		{
			"Cancel",
			"Forget",
			""};

	lv_obj_t *mbox =
		lv_msgbox_create(
			NULL,
			"Forget OpenSky API?",
			"Stored API credentials will be removed.\nDevice will restart.",
			btns,
			false);

	lv_obj_center(mbox);

	lv_obj_add_event_cb(
		mbox,
		api_msgbox_event_cb,
		LV_EVENT_VALUE_CHANGED,
		NULL);
}
