// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void wifi_connect_btn_cb(lv_event_t * e);
void toggleLabels(lv_event_t * e);
void Radar_SelectPrev(lv_event_t * e);
void Radar_SelectNext(lv_event_t * e);
void showRadarSettings(lv_event_t * e);
void editCoords(lv_event_t * e);
void forgetWifi(lv_event_t * e);
void forgetAPI(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
