// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Container8;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label9;
extern void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_ContainerLabels;
extern lv_obj_t * ui_LabelShowLabels;
extern void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_LabelSettingsTitle;
extern lv_obj_t * ui_LabelRadarSettings;
extern lv_obj_t * ui_ContainerRadarFields;
extern void ui_event_TextLat(lv_event_t * e);
extern lv_obj_t * ui_TextLat;
extern void ui_event_TextLon(lv_event_t * e);
extern lv_obj_t * ui_TextLon;
extern void ui_event_TextRange(lv_event_t * e);
extern lv_obj_t * ui_TextRange;
extern void ui_event_TextPoll(lv_event_t * e);
extern lv_obj_t * ui_TextPoll;
extern void ui_event_TextCycle(lv_event_t * e);
extern lv_obj_t * ui_TextCycle;
extern void ui_event_ButtonSaveRadar(lv_event_t * e);
extern lv_obj_t * ui_ButtonSaveRadar;
extern lv_obj_t * ui_LabelSaveRadar;
extern lv_obj_t * ui_ContainerActions;
extern lv_obj_t * ui_KeyboardSettings;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TextLat;
extern lv_obj_t * uic_TextLon;
extern lv_obj_t * uic_TextRange;
extern lv_obj_t * uic_TextPoll;
extern lv_obj_t * uic_TextCycle;
extern lv_obj_t * uic_KeyboardCoord;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
