// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#include "../ui.h"

lv_obj_t * uic_KeyboardCoord;
lv_obj_t * uic_TextLon;
lv_obj_t * uic_TextLat;
lv_obj_t * uic_TextRange;
lv_obj_t * uic_TextPoll;
lv_obj_t * uic_DialogCoord;
lv_obj_t * uic_DialogConfigReq;
lv_obj_t * uic_LabelIPData;
lv_obj_t * uic_LabelIP;
lv_obj_t * uic_LabelWifiName;
lv_obj_t * uic_LabelConnection;
lv_obj_t * uic_PanelBottom;
lv_obj_t * uic_ButtonRight;
lv_obj_t * uic_ButtonLeft;
lv_obj_t * uic_LabelRange;
lv_obj_t * uic_Imageradar;
lv_obj_t * uic_PanelRadar;
lv_obj_t * uic_LabelCraftHeading;
lv_obj_t * uic_LabelCraftCategory;
lv_obj_t * uic_LabelCraftOrigin;
lv_obj_t * uic_LabelCraftSpeed;
lv_obj_t * uic_LabelCraftAlt;
lv_obj_t * uic_LabelCraftName;
lv_obj_t * uic_PanelRight;
lv_obj_t * uic_LabelCoords;
lv_obj_t * uic_LabelAPIRefresh;
lv_obj_t * uic_LabelPlaneCount;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ContainerLeft = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_PanelRight = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ContainerCard4 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_LabelCraftName = NULL;
lv_obj_t * ui_ContainerCard5 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_LabelCraftAlt = NULL;
lv_obj_t * ui_ContainerCard6 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_LabelCraftSpeed = NULL;
lv_obj_t * ui_ContainerCard7 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_LabelCraftOrigin = NULL;
lv_obj_t * ui_ContainerCard9 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_LabelCraftCategory = NULL;
lv_obj_t * ui_ContainerCard10 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_LabelCraftHeading = NULL;
lv_obj_t * ui_PanelRadar = NULL;
lv_obj_t * ui_Imageradar = NULL;
lv_obj_t * ui_ButtonLeft = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_ButtonRight = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_PanelBottom = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LabelWifiName = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_LabelIP = NULL;
lv_obj_t * ui_LabelIPData = NULL;
lv_obj_t * ui_LabelCoords = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_LabelPlaneCount = NULL;
lv_obj_t * ui_LabelAPIRefresh = NULL;
lv_obj_t * ui_ContainerSep1 = NULL;
lv_obj_t * ui_ContainerSep2 = NULL;
lv_obj_t * ui_ContainerSep3 = NULL;
lv_obj_t * ui_DialogConfigReq = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_DialogCoord = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_TextLat = NULL;
lv_obj_t * ui_TextLon = NULL;
lv_obj_t * ui_TextRange = NULL;
lv_obj_t * ui_TextPoll = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_KeyboardCoord = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        showRadarSettings(e);
        _ui_flag_modify(ui_DialogCoord, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ButtonLeft(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Radar_SelectPrev(e);
    }
}

void ui_event_ButtonRight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        Radar_SelectNext(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

void ui_event_TextLat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardCoord,  ui_TextLat);
    }
}

void ui_event_TextLon(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardCoord,  ui_TextLon);
    }
}

void ui_event_TextRange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardCoord, ui_TextRange);
    }
}

void ui_event_TextPoll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_KeyboardCoord, ui_TextPoll);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        editCoords(e);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_DialogCoord, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0A1024), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerLeft = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ContainerLeft);
    lv_obj_set_width(ui_ContainerLeft, 190);
    lv_obj_set_height(ui_ContainerLeft, lv_pct(85));
    lv_obj_set_x(ui_ContainerLeft, 0);
    lv_obj_set_y(ui_ContainerLeft, -25);
    lv_obj_set_align(ui_ContainerLeft, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_ContainerLeft, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ContainerLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_ContainerLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerLeft, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_ContainerLeft);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_Label21, "Flight Radar");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0x08FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Label22, "by Tech Talkies");
    ui_object_set_themeable_style_property(ui_Label22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRight = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRight, 190);
    lv_obj_set_height(ui_PanelRight, lv_pct(85));
    lv_obj_set_x(ui_PanelRight, -5);
    lv_obj_set_y(ui_PanelRight, -25);
    lv_obj_set_align(ui_PanelRight, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_PanelRight, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelRight, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PanelRight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_Container4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);
    lv_obj_set_style_pad_left(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label1, "SELECTED CRAFT");

    ui_ContainerCard4 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerCard4);
    lv_obj_set_height(ui_ContainerCard4, 50);
    lv_obj_set_width(ui_ContainerCard4, lv_pct(100));
    lv_obj_clear_flag(ui_ContainerCard4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContainerCard4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_ContainerCard4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);

    ui_Label17 = lv_label_create(ui_ContainerCard4);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 10);
    lv_obj_set_y(ui_Label17, 2);
    lv_label_set_text(ui_Label17, "Name");
    ui_object_set_themeable_style_property(ui_Label17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label17, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCraftName = lv_label_create(ui_ContainerCard4);
    lv_obj_set_width(ui_LabelCraftName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCraftName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCraftName, 0);
    lv_obj_set_y(ui_LabelCraftName, 2);
    lv_obj_set_align(ui_LabelCraftName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCraftName, "Aircraft");
    lv_obj_set_style_text_color(ui_LabelCraftName, lv_color_hex(0xF98A00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCraftName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCraftName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCard5 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerCard5);
    lv_obj_set_height(ui_ContainerCard5, 50);
    lv_obj_set_width(ui_ContainerCard5, lv_pct(100));
    lv_obj_clear_flag(ui_ContainerCard5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContainerCard5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_ContainerCard5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);

    ui_Label18 = lv_label_create(ui_ContainerCard5);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 10);
    lv_obj_set_y(ui_Label18, 2);
    lv_label_set_text(ui_Label18, "Altitude");
    ui_object_set_themeable_style_property(ui_Label18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label18, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCraftAlt = lv_label_create(ui_ContainerCard5);
    lv_obj_set_width(ui_LabelCraftAlt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCraftAlt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCraftAlt, 0);
    lv_obj_set_y(ui_LabelCraftAlt, 2);
    lv_obj_set_align(ui_LabelCraftAlt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCraftAlt, "0000");
    lv_obj_set_style_text_color(ui_LabelCraftAlt, lv_color_hex(0x00F912), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCraftAlt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCraftAlt, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCard6 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerCard6);
    lv_obj_set_height(ui_ContainerCard6, 50);
    lv_obj_set_width(ui_ContainerCard6, lv_pct(100));
    lv_obj_clear_flag(ui_ContainerCard6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContainerCard6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_ContainerCard6, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);

    ui_Label19 = lv_label_create(ui_ContainerCard6);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 10);
    lv_obj_set_y(ui_Label19, 2);
    lv_label_set_text(ui_Label19, "Speed");
    ui_object_set_themeable_style_property(ui_Label19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label19, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCraftSpeed = lv_label_create(ui_ContainerCard6);
    lv_obj_set_width(ui_LabelCraftSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCraftSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCraftSpeed, 0);
    lv_obj_set_y(ui_LabelCraftSpeed, 2);
    lv_obj_set_align(ui_LabelCraftSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCraftSpeed, "0000");
    lv_obj_set_style_text_color(ui_LabelCraftSpeed, lv_color_hex(0xDDF900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCraftSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCraftSpeed, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCard7 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerCard7);
    lv_obj_set_height(ui_ContainerCard7, 50);
    lv_obj_set_width(ui_ContainerCard7, lv_pct(100));
    lv_obj_clear_flag(ui_ContainerCard7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContainerCard7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_ContainerCard7, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);

    ui_Label20 = lv_label_create(ui_ContainerCard7);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 10);
    lv_obj_set_y(ui_Label20, 2);
    lv_label_set_text(ui_Label20, "Origin");
    ui_object_set_themeable_style_property(ui_Label20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label20, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCraftOrigin = lv_label_create(ui_ContainerCard7);
    lv_obj_set_width(ui_LabelCraftOrigin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCraftOrigin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCraftOrigin, 0);
    lv_obj_set_y(ui_LabelCraftOrigin, 2);
    lv_obj_set_align(ui_LabelCraftOrigin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCraftOrigin, "Wakanda");
    lv_obj_set_style_text_color(ui_LabelCraftOrigin, lv_color_hex(0x00A4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCraftOrigin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCraftOrigin, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCard9 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerCard9);
    lv_obj_set_height(ui_ContainerCard9, 50);
    lv_obj_set_width(ui_ContainerCard9, lv_pct(100));
    lv_obj_clear_flag(ui_ContainerCard9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContainerCard9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_ContainerCard9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);

    ui_Label25 = lv_label_create(ui_ContainerCard9);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 10);
    lv_obj_set_y(ui_Label25, 2);
    lv_label_set_text(ui_Label25, "Category");
    ui_object_set_themeable_style_property(ui_Label25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCraftCategory = lv_label_create(ui_ContainerCard9);
    lv_obj_set_width(ui_LabelCraftCategory, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCraftCategory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCraftCategory, 0);
    lv_obj_set_y(ui_LabelCraftCategory, 5);
    lv_obj_set_align(ui_LabelCraftCategory, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCraftCategory, "UFO");
    lv_obj_set_style_text_color(ui_LabelCraftCategory, lv_color_hex(0x00A4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCraftCategory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCraftCategory, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerCard10 = lv_obj_create(ui_PanelRight);
    lv_obj_remove_style_all(ui_ContainerCard10);
    lv_obj_set_height(ui_ContainerCard10, 50);
    lv_obj_set_width(ui_ContainerCard10, lv_pct(100));
    lv_obj_clear_flag(ui_ContainerCard10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ContainerCard10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_CardBG);
    ui_object_set_themeable_style_property(ui_ContainerCard10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_CardBG);

    ui_Label26 = lv_label_create(ui_ContainerCard10);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 10);
    lv_obj_set_y(ui_Label26, 2);
    lv_label_set_text(ui_Label26, "Heading");
    ui_object_set_themeable_style_property(ui_Label26, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Gray);
    ui_object_set_themeable_style_property(ui_Label26, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Gray);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCraftHeading = lv_label_create(ui_ContainerCard10);
    lv_obj_set_width(ui_LabelCraftHeading, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCraftHeading, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCraftHeading, 0);
    lv_obj_set_y(ui_LabelCraftHeading, 5);
    lv_obj_set_align(ui_LabelCraftHeading, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCraftHeading, "East");
    lv_obj_set_style_text_color(ui_LabelCraftHeading, lv_color_hex(0x00A4F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCraftHeading, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCraftHeading, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRadar = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRadar, 400);
    lv_obj_set_height(ui_PanelRadar, lv_pct(85));
    lv_obj_set_x(ui_PanelRadar, 0);
    lv_obj_set_y(ui_PanelRadar, -25);
    lv_obj_set_align(ui_PanelRadar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelRadar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRadar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRadar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRadar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelRadar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Imageradar = lv_img_create(ui_PanelRadar);
    lv_obj_set_width(ui_Imageradar, 380);
    lv_obj_set_height(ui_Imageradar, 380);
    lv_obj_set_x(ui_Imageradar, 0);
    lv_obj_set_y(ui_Imageradar, -15);
    lv_obj_set_align(ui_Imageradar, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Imageradar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Imageradar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonLeft = lv_btn_create(ui_PanelRadar);
    lv_obj_set_width(ui_ButtonLeft, 50);
    lv_obj_set_height(ui_ButtonLeft, 45);
    lv_obj_set_x(ui_ButtonLeft, 0);
    lv_obj_set_y(ui_ButtonLeft, 10);
    lv_obj_set_align(ui_ButtonLeft, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ButtonLeft, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_ButtonLeft);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "<");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRight = lv_btn_create(ui_PanelRadar);
    lv_obj_set_width(ui_ButtonRight, 50);
    lv_obj_set_height(ui_ButtonRight, 45);
    lv_obj_set_x(ui_ButtonRight, 0);
    lv_obj_set_y(ui_ButtonRight, 10);
    lv_obj_set_align(ui_ButtonRight, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ButtonRight, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_ButtonRight);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, ">");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_PanelRadar);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, 20);
    lv_obj_set_align(ui_Label29, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label29, "Range: 100 km");

    ui_PanelBottom = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_PanelBottom, 50);
    lv_obj_set_width(ui_PanelBottom, lv_pct(99));
    lv_obj_set_x(ui_PanelBottom, 0);
    lv_obj_set_y(ui_PanelBottom, -5);
    lv_obj_set_align(ui_PanelBottom, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PanelBottom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_PanelBottom);
    lv_obj_set_width(ui_Button1, 45);
    lv_obj_set_height(ui_Button1, 45);
    lv_obj_set_align(ui_Button1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_PanelBottom);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_width(ui_Container1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_align(ui_Container1, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "Disconnected:");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFF2E2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWifiName = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelWifiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWifiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelWifiName, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelWifiName, "No WiFi Name");
    lv_obj_set_style_text_font(ui_LabelWifiName, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 1);
    lv_obj_set_height(ui_Container2, 30);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIP = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIP, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelIP, "IP:");
    lv_obj_set_style_text_font(ui_LabelIP, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIPData = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelIPData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIPData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelIPData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelIPData, "0.0.0.0");
    lv_obj_set_style_text_font(ui_LabelIPData, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSep1 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_ContainerSep1);
    lv_obj_set_width(ui_ContainerSep1, 1);
    lv_obj_set_height(ui_ContainerSep1, 30);
    lv_obj_set_align(ui_ContainerSep1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSep1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerSep1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSep1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCoords = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelCoords, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCoords, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCoords, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelCoords, "00.0000, 00.0000");
    lv_obj_set_style_text_color(ui_LabelCoords, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCoords, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCoords, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_Button3, 28);
    lv_obj_set_height(ui_Button3, 28);
    lv_obj_set_align(ui_Button3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_edit_24_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button3, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSep2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_ContainerSep2);
    lv_obj_set_width(ui_ContainerSep2, 1);
    lv_obj_set_height(ui_ContainerSep2, 30);
    lv_obj_set_align(ui_ContainerSep2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSep2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerSep2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSep2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPlaneCount = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelPlaneCount, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPlaneCount, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPlaneCount, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelPlaneCount, "Planes: 0");
    lv_obj_set_style_text_color(ui_LabelPlaneCount, lv_color_hex(0x08FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelPlaneCount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelPlaneCount, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSep3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_ContainerSep3);
    lv_obj_set_width(ui_ContainerSep3, 1);
    lv_obj_set_height(ui_ContainerSep3, 30);
    lv_obj_set_align(ui_ContainerSep3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSep3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContainerSep3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerSep3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAPIRefresh = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_LabelAPIRefresh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAPIRefresh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAPIRefresh, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelAPIRefresh, "Ref: --s");
    lv_obj_set_style_text_color(ui_LabelAPIRefresh, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelAPIRefresh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelAPIRefresh, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DialogConfigReq = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_DialogConfigReq, 300);
    lv_obj_set_height(ui_DialogConfigReq, lv_pct(34));
    lv_obj_set_x(ui_DialogConfigReq, 0);
    lv_obj_set_y(ui_DialogConfigReq, -30);
    lv_obj_set_align(ui_DialogConfigReq, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DialogConfigReq, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_DialogConfigReq);
    lv_obj_set_width(ui_Label3, lv_pct(95));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 10);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Connect to the IP address shown below to configure an API key or data source.");

    ui_Label5 = lv_label_create(ui_DialogConfigReq);
    lv_obj_set_width(ui_Label5, lv_pct(69));
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 12
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label5, "Data source not configured");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label5, lv_color_hex(0x666576), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DialogCoord = lv_obj_create(ui_Screen1);
    lv_obj_set_height(ui_DialogCoord, 414);
    lv_obj_set_width(ui_DialogCoord, lv_pct(100));
    lv_obj_set_x(ui_DialogCoord, 0);
    lv_obj_set_y(ui_DialogCoord, -31);
    lv_obj_set_align(ui_DialogCoord, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DialogCoord, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DialogCoord, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_DialogCoord, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_DialogCoord, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container10 = lv_obj_create(ui_DialogCoord);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, lv_pct(50));
    lv_obj_set_height(ui_Container10, lv_pct(95));
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label16 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label16, "Radar settings");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container10);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_height(ui_Container9, 110);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container9, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextLat = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextLat, 150);
    lv_obj_set_height(ui_TextLat, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextLat, 0);
    lv_obj_set_y(ui_TextLat, -35);
    lv_obj_set_align(ui_TextLat, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextLat, "Latitude");
    lv_textarea_set_one_line(ui_TextLat, true);

    ui_TextLon = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextLon, 150);
    lv_obj_set_height(ui_TextLon, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_TextLon, 0);
    lv_obj_set_y(ui_TextLon, 15);
    lv_obj_set_align(ui_TextLon, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextLon, "Longitude");
    lv_textarea_set_one_line(ui_TextLon, true);

    ui_TextRange = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextRange, 150);
    lv_obj_set_height(ui_TextRange, LV_SIZE_CONTENT);
    lv_textarea_set_placeholder_text(ui_TextRange, "Range (5-200 km)");
    lv_textarea_set_one_line(ui_TextRange, true);

    ui_TextPoll = lv_textarea_create(ui_Container9);
    lv_obj_set_width(ui_TextPoll, 150);
    lv_obj_set_height(ui_TextPoll, LV_SIZE_CONTENT);
    lv_textarea_set_placeholder_text(ui_TextPoll, "Poll (10-120 sec)");
    lv_textarea_set_one_line(ui_TextPoll, true);

    ui_Container7 = lv_obj_create(ui_Container10);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_height(ui_Container7, 50);
    lv_obj_set_width(ui_Container7, lv_pct(100));
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button5, 100);
    lv_obj_set_height(ui_Button5, 50);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Save");

    ui_Button7 = lv_btn_create(ui_Container7);
    lv_obj_set_width(ui_Button7, 100);
    lv_obj_set_height(ui_Button7, 50);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label28 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "Cancel");

    ui_KeyboardCoord = lv_keyboard_create(ui_DialogCoord);
    lv_keyboard_set_mode(ui_KeyboardCoord, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_KeyboardCoord, 349);
    lv_obj_set_height(ui_KeyboardCoord, 301);
    lv_obj_set_align(ui_KeyboardCoord, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLeft, ui_event_ButtonLeft, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRight, ui_event_ButtonRight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextLat, ui_event_TextLat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextLon, ui_event_TextLon, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextRange, ui_event_TextRange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextPoll, ui_event_TextPoll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardCoord, ui_TextLat);
    uic_PanelRight = ui_PanelRight;
    uic_LabelCraftName = ui_LabelCraftName;
    uic_LabelCraftAlt = ui_LabelCraftAlt;
    uic_LabelCraftSpeed = ui_LabelCraftSpeed;
    uic_LabelCraftOrigin = ui_LabelCraftOrigin;
    uic_LabelCraftCategory = ui_LabelCraftCategory;
    uic_LabelCraftHeading = ui_LabelCraftHeading;
    uic_PanelRadar = ui_PanelRadar;
    uic_Imageradar = ui_Imageradar;
    uic_ButtonLeft = ui_ButtonLeft;
    uic_ButtonRight = ui_ButtonRight;
    uic_LabelRange = ui_Label29;
    uic_PanelBottom = ui_PanelBottom;
    uic_LabelConnection = ui_Label2;
    uic_LabelWifiName = ui_LabelWifiName;
    uic_LabelIP = ui_LabelIP;
    uic_LabelIPData = ui_LabelIPData;
    uic_LabelCoords = ui_LabelCoords;
    uic_LabelPlaneCount = ui_LabelPlaneCount;
    uic_LabelAPIRefresh = ui_LabelAPIRefresh;
    uic_DialogConfigReq = ui_DialogConfigReq;
    uic_DialogCoord = ui_DialogCoord;
    uic_TextLat = ui_TextLat;
    uic_TextLon = ui_TextLon;
    uic_TextRange = ui_TextRange;
    uic_TextPoll = ui_TextPoll;
    uic_KeyboardCoord = ui_KeyboardCoord;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ContainerLeft = NULL;
    ui_Container6 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    uic_PanelRight = NULL;
    ui_PanelRight = NULL;
    ui_Container4 = NULL;
    ui_Label1 = NULL;
    ui_ContainerCard4 = NULL;
    ui_Label17 = NULL;
    uic_LabelCraftName = NULL;
    ui_LabelCraftName = NULL;
    ui_ContainerCard5 = NULL;
    ui_Label18 = NULL;
    uic_LabelCraftAlt = NULL;
    ui_LabelCraftAlt = NULL;
    ui_ContainerCard6 = NULL;
    ui_Label19 = NULL;
    uic_LabelCraftSpeed = NULL;
    ui_LabelCraftSpeed = NULL;
    ui_ContainerCard7 = NULL;
    ui_Label20 = NULL;
    uic_LabelCraftOrigin = NULL;
    ui_LabelCraftOrigin = NULL;
    ui_ContainerCard9 = NULL;
    ui_Label25 = NULL;
    uic_LabelCraftCategory = NULL;
    ui_LabelCraftCategory = NULL;
    ui_ContainerCard10 = NULL;
    ui_Label26 = NULL;
    uic_LabelCraftHeading = NULL;
    ui_LabelCraftHeading = NULL;
    uic_PanelRadar = NULL;
    ui_PanelRadar = NULL;
    uic_Imageradar = NULL;
    ui_Imageradar = NULL;
    uic_ButtonLeft = NULL;
    ui_ButtonLeft = NULL;
    ui_Label7 = NULL;
    uic_ButtonRight = NULL;
    ui_ButtonRight = NULL;
    uic_LabelRange = NULL;
    ui_Label11 = NULL;
    ui_Label29 = NULL;
    uic_PanelBottom = NULL;
    ui_PanelBottom = NULL;
    ui_Button1 = NULL;
    ui_Container1 = NULL;
    uic_LabelConnection = NULL;
    ui_Label2 = NULL;
    uic_LabelWifiName = NULL;
    ui_LabelWifiName = NULL;
    ui_Container2 = NULL;
    uic_LabelIP = NULL;
    ui_LabelIP = NULL;
    uic_LabelIPData = NULL;
    ui_LabelIPData = NULL;
    uic_LabelCoords = NULL;
    ui_LabelCoords = NULL;
    ui_Button3 = NULL;
    uic_LabelPlaneCount = NULL;
    ui_LabelPlaneCount = NULL;
    ui_LabelAPIRefresh = NULL;
    ui_LabelAPIRefresh = NULL;
    ui_ContainerSep1 = NULL;
    ui_ContainerSep2 = NULL;
    ui_ContainerSep3 = NULL;
    uic_DialogConfigReq = NULL;
    ui_DialogConfigReq = NULL;
    ui_Label3 = NULL;
    ui_Label5 = NULL;
    uic_DialogCoord = NULL;
    ui_DialogCoord = NULL;
    ui_Container10 = NULL;
    ui_Label16 = NULL;
    ui_Container9 = NULL;
    uic_TextLat = NULL;
    ui_TextLat = NULL;
    uic_TextLon = NULL;
    ui_TextLon = NULL;
    uic_TextRange = NULL;
    ui_TextRange = NULL;
    uic_TextPoll = NULL;
    ui_TextPoll = NULL;
    ui_Container7 = NULL;
    ui_Button5 = NULL;
    ui_Label27 = NULL;
    ui_Button7 = NULL;
    ui_Label28 = NULL;
    uic_KeyboardCoord = NULL;
    ui_KeyboardCoord = NULL;

}
