// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: Flight_radar

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ContainerLeft;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_PanelRight;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ContainerCard4;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_LabelCraftName;
extern lv_obj_t * ui_ContainerCard5;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_LabelCraftAlt;
extern lv_obj_t * ui_ContainerCard6;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_LabelCraftSpeed;
extern lv_obj_t * ui_ContainerCard7;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_LabelCraftOrigin;
extern lv_obj_t * ui_ContainerCard9;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_LabelCraftCategory;
extern lv_obj_t * ui_ContainerCard10;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_LabelCraftHeading;
extern lv_obj_t * ui_PanelRadar;
extern lv_obj_t * ui_Imageradar;
extern void ui_event_ButtonLeft(lv_event_t * e);
extern lv_obj_t * ui_ButtonLeft;
extern lv_obj_t * ui_Label7;
extern void ui_event_ButtonRight(lv_event_t * e);
extern lv_obj_t * ui_ButtonRight;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_PanelBottom;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LabelWifiName;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_LabelIP;
extern lv_obj_t * ui_LabelIPData;
extern lv_obj_t * ui_LabelCoords;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_LabelPlaneCount;
extern lv_obj_t * ui_LabelAPIRefresh;
extern lv_obj_t * ui_ContainerSep1;
extern lv_obj_t * ui_ContainerSep2;
extern lv_obj_t * ui_ContainerSep3;
extern lv_obj_t * ui_DialogConfigReq;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_DialogCoord;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Container9;
extern void ui_event_TextLat(lv_event_t * e);
extern lv_obj_t * ui_TextLat;
extern void ui_event_TextLon(lv_event_t * e);
extern lv_obj_t * ui_TextLon;
extern void ui_event_TextRange(lv_event_t * e);
extern lv_obj_t * ui_TextRange;
extern void ui_event_TextPoll(lv_event_t * e);
extern lv_obj_t * ui_TextPoll;
extern lv_obj_t * ui_Container7;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label27;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_KeyboardCoord;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PanelRight;
extern lv_obj_t * uic_LabelCraftName;
extern lv_obj_t * uic_LabelCraftAlt;
extern lv_obj_t * uic_LabelCraftSpeed;
extern lv_obj_t * uic_LabelCraftOrigin;
extern lv_obj_t * uic_LabelCraftCategory;
extern lv_obj_t * uic_LabelCraftHeading;
extern lv_obj_t * uic_PanelRadar;
extern lv_obj_t * uic_Imageradar;
extern lv_obj_t * uic_ButtonLeft;
extern lv_obj_t * uic_ButtonRight;
extern lv_obj_t * uic_LabelRange;
extern lv_obj_t * uic_PanelBottom;
extern lv_obj_t * uic_LabelConnection;
extern lv_obj_t * uic_LabelWifiName;
extern lv_obj_t * uic_LabelIP;
extern lv_obj_t * uic_LabelIPData;
extern lv_obj_t * uic_LabelCoords;
extern lv_obj_t * uic_LabelPlaneCount;
extern lv_obj_t * uic_LabelAPIRefresh;
extern lv_obj_t * uic_DialogConfigReq;
extern lv_obj_t * uic_DialogCoord;
extern lv_obj_t * uic_TextLat;
extern lv_obj_t * uic_TextLon;
extern lv_obj_t * uic_TextRange;
extern lv_obj_t * uic_TextPoll;
extern lv_obj_t * uic_KeyboardCoord;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
